apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
spec:
  replicas: 2
  selector:
    matchLabels:
      run: php-apache
  template:
    metadata:
      labels:
        run: php-apache
    spec:
      containers:
      - name: php-apache
        image: registry.k8s.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 150m
            # In terms of memory, it's consistently around 128MB
            memory: "128Mi"
          requests:
            # after peak load cpu 0.1 required
            cpu: 100m
            # In terms of memory, it's consistently around 128MB
            memory: "128Mi"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  # minimum 2 pods for nighttime load
  minReplicas: 2
  # 4 pods have been created for peak load
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
      name: memory
      target:
        type: Utilization
        averageUtilization: 80